# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN}


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # main:
        #     id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                  admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/admin
            anonymous:    false
            provider:     in_memory
            form_login:
                login_path: bi_login
                check_path: bi_login_check
                default_target_path: bi_main_admin
            logout:
                path:       bi_logout
                target:     /
            remember_me:
                secret:     %secret%
        admin_login:
            pattern:      ^/login
            anonymous:    true
            provider:     in_memory
        app:
            pattern:      ^/
            anonymous:    ~            