bi_main:
    path: /
    defaults:
        _controller: AppBundle:Main:index



bi_ajax_upvote:
    path: ajax/upvote/{id}
    defaults:
        _controller: AppBundle:Ajax:upvote
    requirements:
        id: .\d*          

bi_ajax_delete_idea:
    path: ajax/delete/idea/{id}
    defaults:
        _controller: AppBundle:Ajax:delete  
    requirements:
        id: .\d*              